import streamlit as st

st.header(":material/star: Certificações")

st.markdown("""
- AWS Cloud Practitioner  
- Cisco CCNA  
- Huawei HCIA 5G / RNP&RNO / Datacom / Routing & Switching
- LPI Linux Essentials  
- MBA em Data Science (USP)
- Alura:
    - Amazon Lightsail: descomplicando a nuvem
    - Avançando com C++: entenda melhor a linguagem
    - C: avançando na linguagem
    - C: conhecendo a Linguagem das Linguagens
    - C: recursos avançados da linguagem
    - C++: Conhecendo a linguagem e a STL
    - Certificação Linux LPI Essentials parte 1: Evolution and Distributions
    - Certificação Linux LPI Essentials parte 10: Where Data is Stored
    - Certificação Linux LPI Essentials parte 11: Your Computer on the Network
    - Certificação Linux LPI Essentials parte 12: Security and File Permissions
    - Certificação Linux LPI Essentials parte 2: Open Source Software and Licensing
    - Certificação Linux LPI Essentials parte 3: Command Line Basics
    - Certificação Linux LPI Essentials parte 4: Using the command line to get help
    - Certificação Linux LPI Essentials parte 5: Directories and Listing Files and managing files
    - Certificação Linux LPI Essentials parte 6: Archiving Files on the Command Line
    - Certificação Linux LPI Essentials parte 7: Searching and Extracting Data from Files
    - Certificação Linux LPI Essentials parte 8: Turning Commands into a Script
    - Certificação Linux LPI Essentials parte 9: Understanding Computer Hardware
    - Deep Learning parte 1: Keras
    - Deep Learning parte 2: como a rede aprende
    - Deploy no Amazon EC2: alta disponibilidade e escalabilidade de uma aplicação
    - Engenharia de Prompt: criando prompts eficazes para IA Generativa
    - Git e GitHub: compartilhando e colaborando em projetos
    - Git e GitHub: dominando controle de versão de código
    - HTML e CSS: ambientes de desenvolvimento, estrutura de arquivos e tags
    - HTML e CSS: Classes, posicionamento e Flexbox
    - HTTP: Entendendo a web por baixo dos panos
    - Introdução à Inteligência Artificial - Sidia
    - Linux I: conhecendo e utilizando o terminal
    - Linux II: programas, processos e pacotes
    - Lógica de programação: explore funções e listas
    - Lógica de programação: mergulhe em programação com JavaScript
    - Machine Learning parte 1: otimização de modelos através de hiperparâmetros
    - Machine Learning parte 2: otimização com exploração aleatória
    - Machine Learning: classificação com SKLearn
    - Machine Learning: validação de modelos
    - Microsserviços: padrões de projeto
    - NumPy: análise numérica eficiente com Python
    - Orientação a Objetos com C++: Classes, métodos e atributos
    - Pandas I/O: trabalhando com diferentes formatos de arquivos
    - Pandas: conhecendo a biblioteca
    - Pandas: limpeza e tratamento de dados
    - Pandas: selecionando e agrupando dados
    - Pandas: transformação e manipulação de dados
    - Python Brasil: validação de dados no padrão nacional
    - Python Collections parte 1: listas e tuplas
    - Python Collections parte 2: conjuntos e dicionários
    - Python e TDD: explorando testes unitários
    - Python para Data Science: primeiros passos
    - Python para Data Science: trabalhando com funções, estruturas de dados e exceções
    - Python: avançando na linguagem
    - Python: avançando na orientação a objetos
    - Python: começando com a linguagem
    - Python: entendendo a Orientação a Objetos
    - String em Python: extraindo informações de uma URL
""")
